# Generated by Django 2.2.1 on 2022-06-27 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='classroom',
            fields=[
                ('room_no', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('course_id', models.CharField(max_length=255)),
                ('capacity', models.IntegerField(blank=True)),
                ('projector', models.IntegerField(blank=True)),
                ('ac', models.IntegerField(blank=True)),
                ('computer', models.IntegerField(blank=True)),
                ('desks', models.IntegerField(blank=True)),
                ('whiteboard', models.IntegerField(blank=True)),
                ('count', models.IntegerField(blank=True)),
                ('type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('course_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('course_fullname', models.CharField(max_length=255)),
                ('course_shortname', models.CharField(max_length=255)),
                ('room_no', models.CharField(max_length=255)),
                ('semester', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='dept',
            fields=[
                ('dept_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('dept_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='faculty_details',
            fields=[
                ('faculty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('faculty_name', models.CharField(max_length=255)),
                ('faculty_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('faculty_rn', models.CharField(max_length=100)),
                ('availability', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='faculty_tt',
            fields=[
                ('faculty_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('course_id', models.CharField(max_length=255)),
                ('course_name', models.CharField(max_length=255)),
                ('ta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='students_2019',
            fields=[
                ('prn', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('student_phone', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=100)),
                ('track', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='timetable_sem6',
            fields=[
                ('start_date', models.DateTimeField(auto_now_add=True, primary_key=True, serialize=False)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('Monday', models.CharField(max_length=255)),
                ('Tuesday', models.CharField(max_length=255)),
                ('Wednesday', models.CharField(max_length=255)),
                ('Thursday', models.CharField(max_length=255)),
                ('Friday', models.CharField(max_length=255)),
                ('Saturday', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='exam',
            fields=[
                ('exam_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('exam_name', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(auto_now_add=True)),
                ('exam_type', models.CharField(max_length=255)),
                ('course_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='iimsApp.course')),
                ('faculty_id', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='iimsApp.faculty_details')),
                ('prn', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='iimsApp.students_2019')),
                ('room_no', models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.DO_NOTHING, to='iimsApp.classroom')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='faculty_id',
            field=models.ForeignKey(max_length=255, on_delete=django.db.models.deletion.CASCADE, to='iimsApp.faculty_details'),
        ),
    ]
